import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="light bg-background text-default-700">
        <Providers themeProps={{ attribute: 'class', defaultTheme: 'light' }} >
      {children}
        </Providers> </body>
    </html>
  );
}
